#!/bin/sh

#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000008-fmriprep/.reproman/jobs/local/20220706-175709-d80f/stdout.%a
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000008-fmriprep/.reproman/jobs/local/20220706-175709-d80f/stderr.%a
#SBATCH --cpus-per-task=2
#SBATCH --array=0-1

/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000008-fmriprep/.reproman/jobs/local/20220706-175709-d80f/runscript $SLURM_ARRAY_TASK_ID